import type { Metadata } from "next";
import { Layout } from "./Components";
import "./globals.css";
import { AppProvider } from "./Context/AuthContext";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Phanox Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Toaster />
          <Layout>{children}</Layout>
        </AppProvider>
      </body>
    </html>
  );
}
